# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
---
image: python:latest

test:
  variables:
    MODE: sim
  script:
    - make test; make clean
