---
image: python:latest

stages:
  - test
  - deploy

test:
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  variables:
    MODE: sim
  script:
    - make lint && make security && make test; make clean

deploy:
  stage: deploy
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
      allow_failure: true
  before_script:
    - which ssh-agent || sudo apt install openssh-client
    - eval "$(ssh-agent -s)"
    - ssh-add <(echo "$SSH_PRIVATE_KEY" | base64 -d)
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - rsync -ae --delete ./ ubuntu@3.230.52.90:./aica-prototype 
    - ssh -o StrictHostKeyChecking=no ubuntu@3.230.52.90 "cd aica-prototype && make rebuild"
