---

security:
  continue-on-vulnerability-error: false
  ignore-cvss-severity-below: 0
  ignore-cvss-unknown-severity: false
  ignore-vulnerabilities:
    71670:
      reason: No newer version available
      expires: '2024-09-30'
