---

services:
  manager:
    environment:
      MODE: "virt"
      TAP_IF: "ens160"
      # This has to go here pending resolution of https://github.com/docker/compose/issues/11404
      HOME_NET: "10.1.200.0/24"
      AICA_MODEL_SERVER: "127.0.0.1:8080"

  ids:
    build: ./ids
    platform: linux/amd64
    container_name: ids
    command: sh /usr/local/bin/docker_entrypoint.sh
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      SURICATA_IF: "ens160"
      # This has to go here pending resolution of https://github.com/docker/compose/issues/11404
      HOME_NET: "10.1.200.0/24"
    network_mode: "host"

include:
  - docker-compose-local-overrides.yaml
