services:
  manager:
    environment:
      MODE: "emu"
      TAP_IF: "eth1"
      HOME_NET: "10.107.100.0/24"
    # For Testing, ensure these containers start with manager
    depends_on:
      siem:
        condition: service_healthy
    networks:
      # Docker brings interfaces up in alphabetical order (except internal, which are last)
      # but this or "tap_net" (in virt mode) should both come up as eth1
      target:
        ipv4_address: 10.107.100.150
  
  siem:
    networks:
      target:
        ipv4_address: 10.107.100.250

  ids:
    build: ./ids
    container_name: ids
    command: sh /usr/local/bin/docker_entrypoint.sh
    cap_add:
      - NET_ADMIN
    environment:
      # Manager/Target host IP only
      SURICATA_IF: "eth0"
      HOME_NET: "10.107.100.150/32,10.107.100.170/32"
    network_mode: service:target

  attacker:
    build: attacker
    container_name: attacker
    env_file:
      - manager/.env
    command: /usr/local/bin/docker_entrypoint.sh
    networks:
      target:
        ipv4_address: 10.107.100.180
    depends_on:
      - target

  target:
    build: target
    container_name: target
    command: /usr/local/bin/docker_entrypoint.sh
    sysctls:
      - net.ipv4.conf.all.forwarding=1
    cap_add:
      - NET_ADMIN  # For iptables/ipset
      - SYS_ADMIN  # For ClamAV on-access scanning (fanotify)
    networks:
      target:
        ipv4_address: 10.107.100.170
    healthcheck:
      test: [ "CMD-SHELL", "ls /tmp | grep eicar" ]
      interval: 10s
      timeout: 10s
      retries: 5
    ports:
      - "80:80"
      - "81:81"
    depends_on:
      - honeypot

  honeypot:
    build: honeypot
    container_name: honeypot
    command: bash -c "source canary/bin/activate && /canary/bin/opencanaryd --dev"
    volumes:
      - ./honeypot/opencanary.conf:/etc/opencanaryd/opencanary.conf
    networks:
      target:
        ipv4_address: 10.107.100.190
  
networks:
  target:
    internal: true
    ipam:
      driver: default
      config:
        - subnet: 10.107.100.0/24 
          ip_range: 10.107.100.128/25
          gateway: 10.107.100.1
