---
version: "3.8"

services:
  manager:
    environment:
      MODE: "emu"
    volumes:
      - ids_suricata_log:/var/log/suricata
      - target_nginx_log:/var/log/nginx

  attacker:
    build: ./attacker
    container_name: 'attacker'
    command: sh /usr/local/bin/docker_entrypoint.sh
    ports:
      - "2222:22"
    networks:
      - target
    tty: true

  target:
    build: ./target
    container_name: 'target'
    command: sh /usr/local/bin/docker_entrypoint.sh
    volumes:
      - target_nginx_log:/var/log/nginx
    sysctls:
      - net.ipv4.conf.all.forwarding=1
    cap_add:
      - NET_ADMIN
    networks:
      - target

  node_red_target:
    build: node_red_target
    container_name: 'node_red_target'
    env_file:
      - 'node_red_target/.env'
    ports:
      - '1880:1880'
    networks:
      - target

  ids:
    build: ./ids
    container_name: 'ids'
    command: sh /usr/local/bin/docker_entrypoint.sh
    volumes:
      - ids_suricata_log:/var/log/suricata
    cap_add:
      - NET_ADMIN
    network_mode: 'service:target'

  honeypot:
    build: ./honeypot
    container_name: 'honeypot'
    command: /usr/bin/opencanaryd --dev
    volumes:
      - ./honeypot/opencanary.conf:/etc/opencanaryd/opencanary.conf
    networks:
      - target

volumes:
  ids_suricata_log:
  target_nginx_log:

networks:
  target:
