---
version: "3.8"

services:
  manager:
    environment:
      MODE: "emu"
    volumes:
      - ids_suricata_log:/var/log/suricata
      - target_nginx_log:/var/log/nginx
      - av_clamav_log:/var/log/clamav

  attacker:
    build: ./attacker
    container_name: 'attacker'
    command: sh /usr/local/bin/docker_entrypoint.sh
    ports:
      - "2222:22"
    networks:
      - target
    tty: true

  target:
    build: ./target
    container_name: 'target'
    command: >
          sh -c "supervisord -c /etc/supervisord.conf"
    volumes:
      - target_nginx_log:/var/log/nginx
      - av_clamav_log:/var/log/clamav
    sysctls:
      - net.ipv4.conf.all.forwarding=1
    cap_add:
      - SYS_ADMIN # Previously NET_ADMIN, has to be SYS because fanotify 
    networks:
      - target
    
  ids:
    build: ./ids
    container_name: 'ids'
    command: sh /usr/local/bin/docker_entrypoint.sh
    volumes:
      - ids_suricata_log:/var/log/suricata
    cap_add:
      - NET_ADMIN
    network_mode: 'service:target'

  honeypot:
    build: ./honeypot
    container_name: 'honeypot'
    command: /usr/bin/opencanaryd --dev
    volumes:
      - ./honeypot/opencanary.conf:/etc/opencanaryd/opencanary.conf
    networks:
      - target

volumes:
  ids_suricata_log:
  target_nginx_log:
  av_clamav_log:

networks:
  target:
