---

services:
  manager:
    environment:
      MODE: "emu"
      TAP_IF: "eth1"
      HOME_NET: "127.0.0.0/8"
    # For Testing, ensure these containers start with manager
    depends_on:
      siem:
        condition: service_healthy

  ids:
    build: ./ids
    platform: linux/amd64
    container_name: ids
    command: sh /usr/local/bin/docker_entrypoint.sh
    cap_add:
      - NET_ADMIN
    environment:
      # Manager/Target host IP only
      SURICATA_IF: "eth0"
      HOME_NET: "127.0.0.0/8"

  attacker:
    build: attacker
    platform: linux/amd64
    container_name: attacker
    env_file:
      - manager/.env
    command: /usr/local/bin/docker_entrypoint.sh
    cap_add:
      - NET_ADMIN  # For nmap, etc
    network_mode: "host"
    depends_on:
      - target

  target:
    build: target
    platform: linux/amd64
    container_name: target
    command: /usr/local/bin/docker_entrypoint.sh
    cap_add:
      - NET_ADMIN  # For iptables/ipset
      - SYS_ADMIN  # For ClamAV on-access scanning (fanotify)
    network_mode: "host"
    healthcheck:
      test: ["CMD-SHELL", "ls /tmp | grep eicar"]
      interval: 10s
      timeout: 10s
      retries: 5
    depends_on:
      - honeypot

  honeypot:
    build: honeypot
    platform: linux/amd64
    container_name: honeypot
    command: bash -c "/usr/local/bin/_entrypoint.sh && /opt/conda/bin/opencanaryd --dev"
    volumes:
      - ./honeypot/opencanary.conf:/etc/opencanaryd/opencanary.conf
    network_mode: "host"