---
name: aica-secprecheck
channels:
  - conda-forge
dependencies:  # MUST BE IDENTICAL VERSIONS TO CORE PACKAGE
  - python=3.11.9
  - jake=3.0.14
  - pip=24.0
  - pyyaml=6.0.1
  # Some things are down here for better cross-platform compatibility
  - pip:
      - bandit==1.7.9
      - safety==3.2.4
