---
name: aica-secprecheck
channels:
  - conda-forge
dependencies:  # MUST BE IDENTICAL VERSIONS TO CORE PACKAGE
  - python=3.11.9
  - jake=3.0.*
  - pip=24.*
  - pyyaml=6.0.*
  # Some things are down here for better cross-platform compatibility
  - pip:
      - bandit==1.7.7
      - safety==3.0.1
