---
name: aica-make
channels:
  - conda-forge
dependencies:
  - python=3.12.4
  - jake=3.0.14
  - mypy=1.10.1
  - pyyaml=6.0.1
  - packaging=24.1
  - yamllint=1.35.1
  - pip=24.0
  # Some things are down here for better cross-platform compatibility
  - pip:
      - bandit==1.7.9
      - bashlint==0.1.1
      - black==24.4.2
      - celery-types==0.22.0
      - charset-normalizer==3.3.2
      - django-stubs==5.0.2
      - networkx-stubs==0.0.1
      - pandas-stubs==2.2.2.240603
      - safety==3.2.4
      - types-requests==2.32.0.20240712
      - types-dateparser==1.2.0.20240420
      - types-openpyxl==3.1.5.20240719
      - types-paramiko==3.4.0.20240423
      - urllib3==2.2.2
