---
name: aica
channels:
  - conda-forge
dependencies:
  - python=3.9
  - black=22.10.0
  - mypy=0.991
  - pylint=2.15.8
  - safety=2.3.5
  - yamllint=1.28.0
  - pip
  - pip:
      - bandit==1.7.4
      - bashlint==0.1.1
      - celery-types==0.14.0
      - django-stubs==1.12.0
      - types-dateparser==1.1.4
      - types-paramiko==2.11.6