---
name: aica
channels:
  - conda-forge
dependencies:
  - python=3.9
  - black=22.6.0
  - mypy=0.982
  - pylint=2.15.3
  - safety=2.1.1
  - yamllint=1.27.1
  - pip
  - pip:
      - bandit==1.7.4
      - bashlint==0.1.1
      - celery-types==0.14.0
      - django-stubs==1.12.0
      - types-dateparser==1.1.4
      - types-paramiko==2.11.6