---
name: aica
channels:
  - conda-forge
dependencies:
  - python=3.9
  - black=23.1.0
  - mypy=1.0.0
  - pylint=2.16.1
  - safety=2.3.5
  - yamllint=1.29.0
  - pip=23.0
  - pip:
      - bandit==1.7.4
      - bashlint==0.1.1
      - celery-types==0.14.0
      - django-stubs==1.14.0
      - types-dateparser==1.1.4.6
      - types-paramiko==3.0.0.2