---
name: base
channels:
  - conda-forge
dependencies:
  - python=3.12.3
  - Django=5.0.6
  - amqp=5.2.0
  - backoff=2.2.1
  - celery=5.3.6
  - coverage=7.4.4
  - dateparser=1.2.0
  - django-extensions=3.2.3
  - flower=2.0.1
  - google-re2=1.1
  - gunicorn=22.0.0
  - joblib=1.4.0
  - kombu=5.3.7
  - networkx=3.3
  - pandas=2.2.2
  - paramiko=3.4.0
  - psycopg2=2.9.9
  - pymongo=4.6.3
  - pyshark=0.6
  - python-dotenv=1.0.1
  - pyyaml=6.0.1
  - requests=2.31.0
  - scikit-learn=1.4.2
  - sqlalchemy=2.0.29
  - watchdog=4.0.0
  - vt-py=0.18.0
  - pip=24.0
  - pip:
      - fasteners==0.19
      - ipwhois==1.2.0
      - mac-vendor-lookup==0.1.12
      - neo4j==5.19.0
      - netaddr==1.2.1
      - netflow==0.12.2
      - netifaces2==0.0.21
      - pecanpy==2.0.9
      - python3-nmap==1.6.0
      - stix2==3.0.1
      - supervisor-stdout==0.1.1
      - torch-geometric==2.5.3
      - torch==2.3.0
      - pylibcugraphops-cu12==24.6.0 