name: CI Test Action

on:
  pull_request:
    branches: [ main ]

env:
  MODE: emu
  ENV_FILE: ${{ secrets.ENV_FILE }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
      
    - name: Run tests
      run:  echo $ENV_FILE | base64 --decode > .env && make deps && make build && make test
