---

name: CI Test Action

on:
  pull_request:
    branches: [main]

env:
  MODE: emu
  ENV_FILE: ${{ secrets.ENV_FILE }}

jobs:
  BuildAndTest:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: mamba-org/setup-micromamba@v1.9.0

      - name: Fetch dependancies
        run: sudo apt-get install libpcap-dev

      - name: Set up and scan environment
        run: echo $ENV_FILE | base64 --decode > manager/.env && make init-core-env

      - name: CI-Specific optimization (Disable GPU)
        run: sed 's/      - torch==/      - --extra-index-url https:\/\/download.pytorch.org\/whl\/cpu\n&/' -i manager/environment-manager.yml

      - name: CI-Specific optimization (Purge Cache)
        run: pip cache purge && micromamba clean -a

      - name: CI-Specific optimization (Lower SIEM message journal max size)
        run: echo "RUN sed -i 's/#message_journal_max_size = 5gb/message_journal_max_size = 500mb/' /usr/share/graylog/data/config/graylog.conf" >> siem/Dockerfile

      - name: Build Containers
        run: make build

      - name: Run tests
        run: make test

      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2
