name: CI Test Action

on:
  pull_request:
    branches: [ main ]

env:
  MODE: emu
  ENV_FILE: ${{ secrets.ENV_FILE }}

jobs:
  BuildAndTest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
      
    - name: Set up environment 
      run:  echo $ENV_FILE | base64 --decode > manager/.env && make deps
    
    - name: Build Containers 
      run:  make build

    - name: Run tests
      run:  make test

    - name: Dump docker logs on failure
      if: failure()
      uses: jwalton/gh-docker-logs@v2
